name: CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Linter
      run: yarn lint

    - name: Test
      env:
        REACT_APP_DEFAULT_NETWORK_ID: 4
      run: yarn test

    - name: Build
      run: yarn build